name: Build, Push, and Deploy to EC2

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: minhnghia12305/frontend-yourlife
  REACT_APP_BACKEND_URL: http://ec2-43-204-233-203.ap-south-1.compute.amazonaws.com:3001/api/v1/

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --build-arg REACT_APP_BACKEND_URL=${{ env.REACT_APP_BACKEND_URL }} -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd /home/${{ secrets.EC2_USER }}/app
            echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" > .env
            docker-compose pull frontend
            docker-compose up -d --remove-orphans frontend
            docker image prune -a -f
          EOF
